# Form implementation generated from reading ui file 'camera_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QWidget

from PyQt6.QtWidgets import QWidget, QLabel, QLineEdit, QPushButton

class Ui_Window(QWidget):
    def setupUi(self, Window):
        Window.setObjectName("Ui_Window")
        Window.resize(350, 200)  # 设置窗口大小

        # 示例：添加一些控件，如标签、文本框、按钮等
        self.label = QLabel("Label", Window)
        self.label.setGeometry(50, 20, 200, 30)  # 设置标签位置和大小

        self.lineEdit = QLineEdit(Window)
        self.lineEdit.setGeometry(50, 60, 200, 30)  # 设置文本框位置和大小

        self.pushButton = QPushButton("Button", Window)
        self.pushButton.setGeometry(50, 100, 200, 30)  # 设置按钮位置和大小

        # 这里可以继续添加更多的控件和布局设置

        # 设置窗口的标题和其他属性
        self.retranslateUi(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Ui_Window", "Camera Settings"))
        # 可以在这里设置其他控件的文本，如按钮文本等

# 如果需要的话，可以在这里添加测试代码或主函数
